on:
  push:
    branches:
      - "prod"
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
        node-version: '20.13.0'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.trainopia.org
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_USER_PASS }}
        protocol: ftps
        local-dir: ./dist/
        log-level: verbose
